### ISSUE TITLE
"Click to open in POB" button doesn't work

### ISSUE THREAD

**Issue by USnikitos** [poediscord/poediscordbot#94]
When you click "Click to open in POB" - browser opens a redirect page as usual, then POB launches - but the build is not imported there, and on the top left in POB after "Current build:" there is an error "Response code: 404".

**Comment by FWidm** [comment]
Hi can you provide me the pobbin/pastebin url you use to generate the embed? I tried with my own and it works on my system.

**Comment by USnikitos** [comment]
huh, now when you said that, I noticed that it works with pobb.in URLs but it doesnt work with poe.ninja - for example https://poe.ninja/pob/lrm

**Comment by FWidm** [comment]
Interesting, that does not work for me either - I'll check it out and let you know when it's fixed :)

**Comment by FWidm** [comment]
It should be fixed now, i had a copy paste error on the redirect site - caches should only last 10 mins so it should hopefully work for you without having to clear caches for [https://fwidm.github.io/pob-redirect/index.html](https://fwidm.github.io/pob-redirect/index.html?pobbin=qO1_QpuQLeDd).

Let me know if this also fixes it for you, works for me now.

**Comment by USnikitos** [comment]
yeah works now! Thank you sir
